services:
  rag-civia-mandate-service:
    image: owldeev/rag-civia-mandate-service:0.6.4-SNAPSHOT
    ports:
      - "8088:8088"
    restart: always
    volumes:
      - [local-key]:[volume-key]
    environment:
      DB_CLUSTER: ""
      DB_KEY: ""
      DB_USER: ""
      DB_NAME: ""
      GEMINI_KEY: ""
      OPENCAGE_KEY: ""
      FIREBASE_JSON_PATH: ""